import type {
  QuestionBankQuestion,
  QuestionBankSubject,
  QuestionBankSubjectId,
} from "@/features/question-bank/types/question-bank-types";

export const questionBankSubjects: QuestionBankSubject[] = [
  {
    id: "mathematics",
    label: "Toán học",
    categories: [
      { id: "fractions", label: "Phân số" },
      { id: "geometry", label: "Hình học" },
      { id: "statistics", label: "Thống kê" },
    ],
  },
  {
    id: "english",
    label: "Tiếng Anh",
    categories: [
      { id: "reading", label: "Reading" },
      { id: "grammar", label: "Grammar" },
      { id: "vocabulary", label: "Vocabulary" },
    ],
  },
  {
    id: "science",
    label: "Khoa học",
    categories: [
      { id: "biology", label: "Sinh học" },
      { id: "physics", label: "Vật lý" },
      { id: "earth", label: "Trái đất" },
    ],
  },
  {
    id: "informatics",
    label: "Tin học",
    categories: [
      { id: "digital-safety", label: "An toàn số" },
      { id: "spreadsheets", label: "Bảng tính" },
      { id: "logic", label: "Tư duy thuật toán" },
    ],
  },
];

export const questionBankQuestions: QuestionBankQuestion[] = [
  {
    id: "qb-math-001",
    subjectId: "mathematics",
    categoryId: "fractions",
    subjectLabel: "Toán học",
    categoryLabel: "Phân số",
    gradeLabel: "Khối 6",
    type: "multiple-choice",
    difficulty: "core",
    status: "ready",
    stem: "Lan ăn 3/8 chiếc bánh và Minh ăn 1/4 chiếc bánh. Tổng cộng hai bạn đã ăn bao nhiêu chiếc bánh?",
    objective: "Cộng hai phân số khác mẫu số cơ bản.",
    tags: ["Phân số", "Khối 6", "Kiểm tra nhanh"],
    masteryRate: 82,
    usageCount: 38,
    schoolsUsing: 7,
    lastUsedAt: "Hôm nay, 08:40",
    recommendedCluster: "Cụm Trung tâm",
    rationale: "Quy đồng 1/4 thành 2/8, sau đó cộng 3/8 + 2/8.",
    choices: [
      { id: "a", label: "5/8", correct: true },
      { id: "b", label: "4/8", correct: false },
      { id: "c", label: "7/12", correct: false },
      { id: "d", label: "1/2", correct: false },
    ],
  },
  {
    id: "qb-math-002",
    subjectId: "mathematics",
    categoryId: "geometry",
    subjectLabel: "Toán học",
    categoryLabel: "Hình học",
    gradeLabel: "Khối 7",
    type: "numeric",
    difficulty: "stretch",
    status: "ready",
    stem: "Một hình chữ nhật có chiều dài 12 cm và chiều rộng 7 cm. Chu vi của hình là bao nhiêu?",
    objective: "Tính chu vi hình chữ nhật.",
    tags: ["Hình học", "Khối 7", "Chu vi"],
    masteryRate: 76,
    usageCount: 29,
    schoolsUsing: 5,
    lastUsedAt: "Hôm qua, 16:20",
    recommendedCluster: "Cụm Đông Bắc",
    answer: "38",
    rationale: "Chu vi hình chữ nhật bằng (dài + rộng) x 2.",
  },
  {
    id: "qb-math-003",
    subjectId: "mathematics",
    categoryId: "statistics",
    subjectLabel: "Toán học",
    categoryLabel: "Thống kê",
    gradeLabel: "Khối 8",
    type: "true-false",
    difficulty: "core",
    status: "reviewing",
    stem: "Phát biểu sau đúng hay sai: Trung vị luôn bằng trung bình cộng.",
    objective: "Phân biệt trung vị và trung bình cộng.",
    tags: ["Thống kê", "Khối 8", "Khái niệm"],
    masteryRate: 61,
    usageCount: 14,
    schoolsUsing: 4,
    lastUsedAt: "2 ngày trước",
    recommendedCluster: "Cụm Nam Sài Gòn",
    answer: "Sai",
    rationale: "Trung vị và trung bình cộng chỉ trùng nhau trong một số tập dữ liệu đặc biệt.",
  },
  {
    id: "qb-eng-001",
    subjectId: "english",
    categoryId: "reading",
    subjectLabel: "Tiếng Anh",
    categoryLabel: "Reading",
    gradeLabel: "Khối 6",
    type: "multiple-choice",
    difficulty: "core",
    status: "ready",
    stem: "Read the sentence: 'Mai walks to school every day because it is near her house.' Why does Mai walk to school?",
    objective: "Xác định thông tin trực tiếp trong câu đọc hiểu ngắn.",
    tags: ["Reading", "Daily routine", "Starter"],
    masteryRate: 88,
    usageCount: 46,
    schoolsUsing: 8,
    lastUsedAt: "Hôm nay, 10:05",
    recommendedCluster: "Cụm Trung tâm",
    choices: [
      { id: "a", label: "Because she likes running.", correct: false },
      { id: "b", label: "Because the school is near her house.", correct: true },
      { id: "c", label: "Because her bike is broken.", correct: false },
      { id: "d", label: "Because her friends walk with her.", correct: false },
    ],
  },
  {
    id: "qb-eng-002",
    subjectId: "english",
    categoryId: "grammar",
    subjectLabel: "Tiếng Anh",
    categoryLabel: "Grammar",
    gradeLabel: "Khối 7",
    type: "fill-in-the-blanks",
    difficulty: "stretch",
    status: "ready",
    stem: "Complete the sentence: 'If she ___ enough time, she will finish the project tonight.'",
    objective: "Nhận diện mệnh đề if loại 1.",
    tags: ["Grammar", "If clause", "Khối 7"],
    masteryRate: 69,
    usageCount: 24,
    schoolsUsing: 6,
    lastUsedAt: "3 ngày trước",
    recommendedCluster: "Cụm Đông Bắc",
    answer: "has",
    rationale: "Mệnh đề if loại 1 dùng hiện tại đơn ở mệnh đề if.",
  },
  {
    id: "qb-eng-003",
    subjectId: "english",
    categoryId: "vocabulary",
    subjectLabel: "Tiếng Anh",
    categoryLabel: "Vocabulary",
    gradeLabel: "Khối 6",
    type: "multiple-response",
    difficulty: "core",
    status: "pilot",
    stem: "Select all words that describe positive study habits.",
    objective: "Mở rộng vốn từ về thói quen học tập.",
    tags: ["Vocabulary", "Study skills", "Multiple select"],
    masteryRate: 72,
    usageCount: 18,
    schoolsUsing: 3,
    lastUsedAt: "Tuần trước",
    recommendedCluster: "Cụm Nam Sài Gòn",
    choices: [
      { id: "a", label: "organized", correct: true },
      { id: "b", label: "careless", correct: false },
      { id: "c", label: "curious", correct: true },
      { id: "d", label: "lazy", correct: false },
    ],
  },
  {
    id: "qb-sci-001",
    subjectId: "science",
    categoryId: "biology",
    subjectLabel: "Khoa học",
    categoryLabel: "Sinh học",
    gradeLabel: "Khối 6",
    type: "multiple-choice",
    difficulty: "core",
    status: "ready",
    stem: "Bộ phận nào của cây có vai trò hút nước và muối khoáng từ đất?",
    objective: "Nhận biết chức năng cơ bản của rễ cây.",
    tags: ["Sinh học", "Thực vật", "Cơ bản"],
    masteryRate: 91,
    usageCount: 40,
    schoolsUsing: 7,
    lastUsedAt: "Hôm nay, 09:30",
    recommendedCluster: "Cụm Trung tâm",
    choices: [
      { id: "a", label: "Lá", correct: false },
      { id: "b", label: "Hoa", correct: false },
      { id: "c", label: "Rễ", correct: true },
      { id: "d", label: "Quả", correct: false },
    ],
  },
  {
    id: "qb-sci-002",
    subjectId: "science",
    categoryId: "physics",
    subjectLabel: "Khoa học",
    categoryLabel: "Vật lý",
    gradeLabel: "Khối 8",
    type: "short-answer",
    difficulty: "stretch",
    status: "reviewing",
    stem: "Nêu một ví dụ về lực ma sát có lợi trong đời sống hằng ngày.",
    objective: "Liên hệ kiến thức lực ma sát với thực tế.",
    tags: ["Vật lý", "Ứng dụng", "Tự luận ngắn"],
    masteryRate: 66,
    usageCount: 17,
    schoolsUsing: 4,
    lastUsedAt: "2 ngày trước",
    recommendedCluster: "Cụm Đông Bắc",
    answer: "Ví dụ: ma sát giữa lốp xe và mặt đường giúp xe di chuyển an toàn.",
  },
  {
    id: "qb-sci-003",
    subjectId: "science",
    categoryId: "earth",
    subjectLabel: "Khoa học",
    categoryLabel: "Trái đất",
    gradeLabel: "Khối 7",
    type: "multiple-choice",
    difficulty: "challenge",
    status: "ready",
    stem: "Hiện tượng ngày và đêm trên Trái Đất xảy ra chủ yếu do nguyên nhân nào?",
    objective: "Hiểu chuyển động tự quay của Trái Đất.",
    tags: ["Trái đất", "Thiên văn", "Khối 7"],
    masteryRate: 74,
    usageCount: 26,
    schoolsUsing: 6,
    lastUsedAt: "Hôm qua, 13:10",
    recommendedCluster: "Cụm Nam Sài Gòn",
    choices: [
      { id: "a", label: "Trái Đất quay quanh Mặt Trăng", correct: false },
      { id: "b", label: "Trái Đất tự quay quanh trục của nó", correct: true },
      { id: "c", label: "Mặt Trời tự quay quanh Trái Đất", correct: false },
      { id: "d", label: "Mặt Trăng che ánh sáng Mặt Trời", correct: false },
    ],
  },
  {
    id: "qb-it-001",
    subjectId: "informatics",
    categoryId: "digital-safety",
    subjectLabel: "Tin học",
    categoryLabel: "An toàn số",
    gradeLabel: "Khối 6",
    type: "multiple-choice",
    difficulty: "core",
    status: "ready",
    stem: "Mật khẩu nào sau đây an toàn hơn cho tài khoản học tập trực tuyến?",
    objective: "Nhận diện nguyên tắc tạo mật khẩu mạnh.",
    tags: ["An toàn số", "Password", "Khối 6"],
    masteryRate: 94,
    usageCount: 52,
    schoolsUsing: 9,
    lastUsedAt: "Hôm nay, 11:12",
    recommendedCluster: "Cụm Trung tâm",
    choices: [
      { id: "a", label: "12345678", correct: false },
      { id: "b", label: "ngaySinhEm", correct: false },
      { id: "c", label: "Erg@2026!Learn", correct: true },
      { id: "d", label: "abcdefg", correct: false },
    ],
  },
  {
    id: "qb-it-002",
    subjectId: "informatics",
    categoryId: "spreadsheets",
    subjectLabel: "Tin học",
    categoryLabel: "Bảng tính",
    gradeLabel: "Khối 7",
    type: "multiple-choice",
    difficulty: "stretch",
    status: "ready",
    stem: "Trong bảng tính, công thức nào dùng để tính tổng giá trị từ ô B2 đến B8?",
    objective: "Sử dụng hàm SUM trong bảng tính.",
    tags: ["Spreadsheet", "Formula", "Khối 7"],
    masteryRate: 79,
    usageCount: 31,
    schoolsUsing: 7,
    lastUsedAt: "Hôm qua, 17:45",
    recommendedCluster: "Cụm Đông Bắc",
    choices: [
      { id: "a", label: "=SUM(B2:B8)", correct: true },
      { id: "b", label: "=ADD(B2-B8)", correct: false },
      { id: "c", label: "=TOTAL(B2:B8)", correct: false },
      { id: "d", label: "=B2+B8", correct: false },
    ],
  },
  {
    id: "qb-it-003",
    subjectId: "informatics",
    categoryId: "logic",
    subjectLabel: "Tin học",
    categoryLabel: "Tư duy thuật toán",
    gradeLabel: "Khối 8",
    type: "sequence",
    difficulty: "challenge",
    status: "pilot",
    stem: "Sắp xếp các bước hợp lý để kiểm tra và sửa lỗi trong một thuật toán đơn giản.",
    objective: "Rèn năng lực tư duy tuần tự và gỡ lỗi.",
    tags: ["Algorithm", "Sequence", "Khối 8"],
    masteryRate: 58,
    usageCount: 9,
    schoolsUsing: 2,
    lastUsedAt: "Tuần trước",
    recommendedCluster: "Cụm Nam Sài Gòn",
    rationale: "Quan sát đầu vào, chạy thử, xác định bước sai, chỉnh sửa và kiểm tra lại.",
  },
];

export function getQuestionBankSubject(subjectId: QuestionBankSubjectId) {
  return questionBankSubjects.find((subject) => subject.id === subjectId) ?? questionBankSubjects[0];
}

export function getQuestionBankCategoryCount(subjectId: QuestionBankSubjectId, categoryId: string) {
  return questionBankQuestions.filter(
    (question) => question.subjectId === subjectId && question.categoryId === categoryId,
  ).length;
}
