import type {
  StudentDashboardAssignment,
  StudentDashboardProfile,
  StudentLeaderboardEntry,
} from "@/features/student-dashboard/types/student-dashboard-types";
import { sampleQuiz } from "@/lib/sample-quiz";

export const studentDashboardProfile: StudentDashboardProfile = {
  id: "student-current",
  name: "Võ Ngọc Linh",
  className: "Lớp 6A1",
  gradeLabel: "Khối 6",
  schoolName: "ERG Alpha Campus",
  homeroomTeacher: "Ngọc Anh",
  averageScore: 91,
  completedAssignments: 18,
  totalAssignments: 24,
  classRank: 2,
  gradeRank: 5,
  motivationPoints: 1240,
  weeklyGoalProgress: 78,
};

export const studentAssignments: StudentDashboardAssignment[] = [
  {
    id: "assignment-active",
    quizId: sampleQuiz.id,
    title: sampleQuiz.title,
    subtitle: "Ôn tập kỹ năng tương tác cốt lõi",
    subjectLabel: "Tin học",
    teacherName: "Nguyễn Phát Tài",
    status: "in_progress",
    progressRate: 67,
    answeredCount: 4,
    totalQuestions: 6,
    score: null,
    maxScore: 60,
    dueLabel: "Hạn nộp hôm nay, 20:30",
    statusLabel: "Đang làm",
    lastActivityLabel: "Hoạt động 12 phút trước",
    focusNote: "Bạn đang đi đúng nhịp, chỉ còn 2 câu nữa để hoàn thành bài.",
  },
  {
    id: "assignment-english",
    quizId: sampleQuiz.id,
    title: "Reading Sprint - Daily Routines",
    subtitle: "Đọc hiểu và chọn đáp án nhanh",
    subjectLabel: "Tiếng Anh",
    teacherName: "Trần Thu Hà",
    status: "not_started",
    progressRate: 0,
    answeredCount: 0,
    totalQuestions: 10,
    score: null,
    maxScore: 100,
    dueLabel: "Hạn nộp ngày mai, 09:00",
    statusLabel: "Chưa bắt đầu",
    lastActivityLabel: "Mới được giao 2 giờ trước",
    focusNote: "Ưu tiên làm trước 21:00 để giữ chuỗi hoàn thành trong tuần.",
  },
  {
    id: "assignment-math",
    quizId: sampleQuiz.id,
    title: "Luyện phân số và quy đồng",
    subtitle: "Bài tập về nhà tuần 4",
    subjectLabel: "Toán học",
    teacherName: "Lê Thị Mỹ Duyên",
    status: "submitted",
    progressRate: 100,
    answeredCount: 12,
    totalQuestions: 12,
    score: 94,
    maxScore: 100,
    dueLabel: "Đã nộp đúng hạn",
    statusLabel: "Đã nộp",
    lastActivityLabel: "Nộp hôm qua, 21:04",
    focusNote: "Điểm rất tốt, chỉ cần rà lại 1 câu vận dụng cuối.",
  },
  {
    id: "assignment-science",
    quizId: sampleQuiz.id,
    title: "Khoa học - Lực ma sát",
    subtitle: "Tự luận ngắn kết hợp trắc nghiệm",
    subjectLabel: "Khoa học",
    teacherName: "Phạm Gia Bảo",
    status: "overdue",
    progressRate: 35,
    answeredCount: 3,
    totalQuestions: 8,
    score: null,
    maxScore: 80,
    dueLabel: "Quá hạn 1 ngày",
    statusLabel: "Quá hạn",
    lastActivityLabel: "Dừng lại từ hôm qua, 18:15",
    focusNote: "Cần hoàn tất sớm để không mất điểm thi đua tuần.",
  },
];

export const classLeaderboard: StudentLeaderboardEntry[] = [
  {
    id: "class-rank-1",
    name: "Lê Gia Hân",
    schoolName: "ERG Alpha Campus",
    className: "Lớp 6A1",
    averageScore: 95,
    completedAssignments: 19,
    motivationPoints: 1288,
    badge: "Top 1 lớp",
  },
  {
    id: "class-rank-2",
    name: "Võ Ngọc Linh",
    schoolName: "ERG Alpha Campus",
    className: "Lớp 6A1",
    averageScore: 91,
    completedAssignments: 18,
    motivationPoints: 1240,
    badge: "Bám đuổi sát",
    isCurrentStudent: true,
  },
  {
    id: "class-rank-3",
    name: "Nguyễn Minh Khôi",
    schoolName: "ERG Alpha Campus",
    className: "Lớp 6A1",
    averageScore: 88,
    completedAssignments: 17,
    motivationPoints: 1170,
    badge: "Giữ nhịp tốt",
  },
];

export const gradeLeaderboard: StudentLeaderboardEntry[] = [
  {
    id: "grade-rank-1",
    name: "Lê Gia Hân",
    schoolName: "ERG Alpha Campus",
    className: "Lớp 6A1",
    averageScore: 95,
    completedAssignments: 19,
    motivationPoints: 1288,
    badge: "Top khối",
  },
  {
    id: "grade-rank-2",
    name: "Phan Thiện Phúc",
    schoolName: "ERG South Studio",
    className: "Lớp 6M1",
    averageScore: 93,
    completedAssignments: 18,
    motivationPoints: 1266,
    badge: "Đối thủ mạnh",
  },
  {
    id: "grade-rank-3",
    name: "Trần Gia Bảo",
    schoolName: "ERG East Learning Point",
    className: "Lớp 6C2",
    averageScore: 92,
    completedAssignments: 18,
    motivationPoints: 1251,
    badge: "Ổn định cao",
  },
  {
    id: "grade-rank-5",
    name: "Võ Ngọc Linh",
    schoolName: "ERG Alpha Campus",
    className: "Lớp 6A1",
    averageScore: 91,
    completedAssignments: 18,
    motivationPoints: 1240,
    badge: "Top 5 khối",
    isCurrentStudent: true,
  },
];
